Repository GonggakSim/Backend, pull requests merged in 2025-01, with the labels that each got.

#3 [FEAT] deploy pipeline 설정
  .github/workflows/deploy.yml
  package-lock.json
  package.json
Labels: :sparkles: feature

#7 #6 [REFACT] 스웨거, deploy 환경 수정
  .github/workflows/deploy-main.yml
  .github/workflows/test-main.yml
  dist/index.cjs
  package-lock.json
  package.json
  scripts/build.ts
Labels: :recycle: refactor

#10 Feature/8/add test pipiline
  .github/workflows/deploy-main.yml
  .github/workflows/test-dev.yml
  .github/workflows/test-main.yml
  dist/index.cjs
  package-lock.json
  package.json
  scripts/build.ts
  src/auth.config.ts
  src/db.config.ts
  src/index.ts
Labels: :sparkles: feature

#13 # 11 [FEAT] sns 로그인 설정
  @types/environment.d.ts
  package-lock.json
  package.json
  prisma/migrations/20250109113241_update_user/migration.sql
  prisma/migrations/20250109201922_update_user_login/migration.sql
  prisma/migrations/20250110054935_update_oauth_token_length/migration.sql
  prisma/schema.prisma
  src/auth.config.ts
  src/index.ts
  src/router/googleRouts.ts
  src/router/kakaoRouts.ts
Labels: :sparkles: feature

#15 #14 [FEAT] sns 로그아웃 기능
  src/index.ts
  src/router/authRoutes.ts
Labels: :sparkles: feature

#23 #19 [FEAT] 캘린더 사용자 시험 추가 시 리마인드 알림 기능
  .gitignore
  package-lock.json
  package.json
  prisma/migrations/20250115090133_add_fcm_token_to_user/migration.sql
  prisma/schema.prisma
  src/controllers/exam.controller.ts
  src/dtos/exam.dto.ts
  src/index.ts
  src/repositories/exam.repository.ts
  src/services/exam.service.ts
  src/utils/fcm.utils.ts
  src/utils/notification.utils.ts
  tsconfig.json
Labels: :sparkles: feature

#26 #21 Refactor 토큰 관리 방법 수정
  @types/environment.d.ts
  @types/express.d.ts
  package-lock.json
  package.json
  prisma/migrations/20250117162246_update_session/migration.sql
  prisma/schema.prisma
  src/auth.config.ts
  src/controllers/auth.controller.ts
  src/controllers/user.controller.ts
  src/index.ts
  src/middlewares/auth.middleware.ts
  src/router/googleRouts.ts
  src/router/kakaoRouts.ts
  src/routes/authRoutes.ts
  src/routes/googleRouts.ts
  src/routes/kakaoRouts.ts
  src/routes/naverRouts.ts
  src/routes/userRoutes.ts
  src/services/auth.service.ts
  src/services/user.service.ts
  src/utils/auth.utils.ts
Labels: :recycle: refactor

#29 #19 FEAT GPT AI 시험 일정 추천 기능
  package-lock.json
  package.json
  src/controllers/schedule.controller.ts
  src/dtos/schedule.dto.ts
  src/index.ts
  src/repositories/schedule.repository.ts
  src/services/schedule.service.ts
  src/utils/dateUtils.ts
  src/utils/openai.ts
Labels: :sparkles: feature

#30 #19 FEAT GPT AI 시험 일정 추천 기능
  src/services/schedule.service.ts
  src/utils/openai.ts
Labels: :sparkles: feature

#31 #27 이용약관 동의 기능
  src/controllers/consent.controller.ts
  src/index.ts
  src/routes/authRoutes.ts
Labels: :sparkles: feature

#34 [REFACT] FCM 토큰 관리
  prisma/migrations/20250119064437_add_fcm_token/migration.sql
  prisma/schema.prisma
  src/dtos/exam.dto.ts
  src/repositories/exam.repository.ts
  src/services/exam.service.ts
  src/utils/fcm.utils.ts
  src/utils/notification.utils.ts
Labels: :recycle: refactor

#35 #32 회원탈퇴 기능
  package-lock.json
  prisma/migrations/20250118205702_update_user_category/migration.sql
  prisma/migrations/20250119082131_update_user/migration.sql
  prisma/migrations/20250119114148_update_user_cascade/migration.sql
  prisma/schema.prisma
  src/controllers/auth.controller.ts
  src/controllers/consent.controller.ts
  src/dtos/user.dto.ts
  src/middlewares/auth.middleware.ts
  src/repositories/user.repository.ts
  src/routes/authRoutes.ts
  src/services/auth.service.ts
Labels: :sparkles: feature

#45 #44 FEAT 자격증 검색 기능
  package-lock.json
  src/controllers/certification.controller.ts
  src/dtos/certification.dto.ts
  src/dtos/schedule.dto.ts
  src/index.ts
  src/repositories/certification.respository.ts
  src/repositories/user.repository.ts
  src/services/certification.service.ts
  src/services/schedule.service.ts
  src/utils/dateUtils.ts
  src/utils/openai.ts
Labels: :sparkles: feature

#51 #41 gpt AI 시험 일정 추천 기능 수정
  src/utils/openai.ts
Labels: :recycle: refactor

#56 #54 캘린더 리마인드 알림 리팩토링, FCM 토큰 관리 수정
  git
  prisma/migrations/20250122052420_remove_fcm_token_from_exam/migration.sql
  prisma/migrations/20250122055322_add_fcm_token/migration.sql
  prisma/schema.prisma
  src/repositories/exam.repository.ts
  src/services/exam.service.ts
  src/utils/fcm.utils.ts
  src/utils/notification.utils.ts
Labels: :recycle: refactor

#57 #54 방해 금지 모드 설정 및 알림 관련 기능 수정
  package-lock.json
  package.json
  prisma/migrations/20250123130203_modify_the_type_of_notification_fields/migration.sql
  prisma/schema.prisma
  src/controllers/exam.controller.ts
  src/controllers/notification.controller.ts
  src/dtos/exam.dto.ts
  src/dtos/notificationSettings.dto.ts
  src/index.ts
  src/repositories/exam.repository.ts
  src/repositories/notification.repository.ts
  src/services/exam.service.ts
  src/services/notification.service.ts
  src/utils/fcm.utils.ts
  src/utils/notification.utils.ts
Labels: :sparkles: feature, :recycle: refactor

#59 #58 방해 금지 모드 로직 수정 및 FCM 토큰 관리
  src/dtos/notificationSettings.dto.ts
  src/repositories/notification.repository.ts
  src/services/notification.service.ts
  src/utils/fcm.utils.ts
  src/utils/notification.utils.ts
Labels: :recycle: refactor

#67 #60 캘린더 추가, 조회, 삭제, AI 일정 추천, 자격증 검색, DND 시간대 설정 Swagger 문서 작성
  build/swagger.yaml
  src/controllers/exam.controller.ts
  src/controllers/notification.controller.ts
  src/index.ts
  src/swagger/openapi.yaml
Labels: 📝 documentation

#70 [Deploy] update main
  build/swagger.yaml
  src/auth.config.ts
  src/controllers/exam.controller.ts
  src/controllers/notification.controller.ts
  src/index.ts
  src/routes/userRoutes.ts
  src/services/auth.service.ts
  src/swagger/openapi.yaml
Labels: :sparkles: feature

#72 #71 마이페이지 조회 기능
  build/swagger.yaml
  src/controllers/user.controller.ts
  src/routes/userRoutes.ts
  src/services/user.service.ts
  src/swagger/openapi.yaml
Labels: :sparkles: feature

#76 #68 로그인 토큰 방식 변경
  build/swagger.yaml
  prisma/migrations/20250128181118_update_schedule/migration.sql
  src/auth.config.ts
  src/controllers/auth.controller.ts
  src/index.ts
  src/middlewares/auth.middleware.ts
  src/routes/authRoutes.ts
  src/routes/googleRoutes.ts
  src/routes/kakaoRoutes.ts
  src/routes/naverRoutes.ts
  src/services/auth.service.ts
Labels: :recycle: refactor

#80 #74 Prisma Exam 필드 변경과 API 구조 수정
  build/swagger.yaml
  package-lock.json
  package.json
  prisma/migrations/20250129073243_update_exam/migration.sql
  prisma/migrations/20250129093035_edit_exam_fields/migration.sql
  prisma/migrations/20250130012621_update_exam_exam_start_field/migration.sql
  prisma/schema.prisma
  src/dtos/exam.dto.ts
  src/repositories/exam.repository.ts
  src/services/exam.service.ts
  src/services/user.service.ts
  src/swagger/openapi.yaml
  src/utils/notification.utils.ts
Labels: :recycle: refactor
