Repository GonggakSim/Backend, pull requests merged in 2025-02, with the labels that each got.

#84 #74 스웨거 문서 provider 추가
  build/swagger.yaml
  src/swagger/openapi.yaml
Labels: 📝 documentation

#86 #85 구글 클라이언트 수정
  @types/environment.d.ts
  src/auth.config.ts
  src/routes/googleRoutes.ts
  src/services/auth.service.ts
  src/utils/auth.utils.ts
Labels: :recycle: refactor

#91 #90 AI 시험 일정 추천 수정
  src/repositories/schedule.repository.ts
  src/utils/openai.ts
Labels: :recycle: refactor

#92 #88 swagger와 유사 사용자 추천 수정
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  build/swagger.yaml
  src/dtos/user.dto.ts
  src/repositories/user.repository.ts
  src/services/user.service.ts
  src/swagger/openapi.yaml
Labels: :recycle: refactor

#96 [FEAT] 요구에 따른 퀴즈 보내기, 퀴즈 정답 유무 기능
  build/swagger.yaml
  src/controllers/quiz.controller.ts
  src/firebase.ts
  src/index.ts
  src/repositories/quiz.repository.ts
  src/routes/quizRoutes.ts
  src/services/quiz.service.ts
Labels: :sparkles: feature

#97 #95 닉네임 수정/저장 기능
  build/swagger.yaml
  src/controllers/user.controller.ts
  src/routes/userRoutes.ts
  src/services/user.service.ts
  src/swagger/openapi.yaml
Labels: :sparkles: feature

#103 #102 방해 금지 시간대 설정 함수 수정
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  src/utils/notification.utils.ts
Labels: :recycle: refactor

#108 #102 방해 금지 시간대 설정 코드 리팩토링 및 프리즈마 수
  package-lock.json
  package.json
  prisma/migrations/20250208121046_edit_notification_field/migration.sql
  prisma/schema.prisma
  src/controllers/notification.controller.ts
  src/dtos/notificationSettings.dto.ts
  src/repositories/notification.repository.ts
  src/services/notification.service.ts
  src/utils/openai.ts
Labels: :recycle: refactor

#109 #104 토큰 관리 방법 수정
  @types/environment.d.ts
  src/controllers/auth.controller.ts
  src/index.ts
  src/middlewares/auth.middleware.ts
  src/routes/authRoutes.ts
  src/routes/certificationAlramRoutes.ts
  src/routes/examRoutes.ts
  src/routes/googleRoutes.ts
  src/routes/kakaoRoutes.ts
  src/routes/naverRoutes.ts
  src/routes/quizRoutes.ts
  src/routes/scheduleRoutes.ts
  src/routes/userRoutes.ts
  src/services/auth.service.ts
  src/utils/jwt.utils.ts
Labels: :recycle: refactor

#113 #111 알림 스케줄링 최적화
  src/utils/notification.utils.ts
Labels: :recycle: refactor

#117 [#116] cors 설정 수정
  build/swagger.yaml
  src/auth.config.ts
  src/index.ts
  src/routes/googleRoutes.ts
  src/swagger/openapi.yaml
Labels: :recycle: refactor

#118 [Deploy] Update dev
  build/swagger.yaml
  src/auth.config.ts
  src/controllers/schedule.controller.ts
  src/index.ts
  src/routes/googleRoutes.ts
  src/swagger/openapi.yaml
  src/utils/notification.utils.ts
Labels: :recycle: refactor

#130 [REFACT] 퀴즈 데이터 DB 파베 -> 몽고 변경으로 인한 로직 변경
  src/index.ts
  src/models/AttemptedQuiz.ts
  src/models/QuizQuestion.ts
  src/repositories/quiz.repository.ts
  src/services/quiz.service.ts
Labels: :recycle: refactor

#131 [#128] 인증 관련 전체 api 수정
  .github/workflows/deploy-main.yml
  build/swagger.yaml
  package.json
  src/controllers/auth.controller.ts
  src/controllers/user.controller.ts
  src/routes/authRoutes.ts
  src/services/auth.service.ts
  src/services/user.service.ts
  src/swagger/openapi.yaml
  src/utils/auth.utils.ts
Labels: :recycle: refactor

#132 [#112] 유사 사용자 시험 추천 기능
  .github/workflows/deploy-main.yml
  package.json
  src/repositories/user.repository.ts
  src/services/user.service.ts
Labels: :recycle: refactor

#133 [Deploy] Update dev
  build/swagger.yaml
  package.json
  src/controllers/auth.controller.ts
  src/controllers/user.controller.ts
  src/index.ts
  src/models/AttemptedQuiz.ts
  src/models/QuizQuestion.ts
  src/repositories/quiz.repository.ts
  src/repositories/user.repository.ts
  src/routes/authRoutes.ts
  src/services/auth.service.ts
  src/services/quiz.service.ts
  src/services/user.service.ts
  src/swagger/openapi.yaml
  src/utils/auth.utils.ts
Labels: :recycle: refactor

#135 [#122] 에러 처리 통일 및 캘린더, 자격증 검색 API 리팩토링
  package-lock.json
  package.json
  src/controllers/certification.controller.ts
  src/controllers/exam.controller.ts
  src/dtos/certification.dto.ts
  src/repositories/certification.respository.ts
  src/repositories/exam.repository.ts
  src/services/auth.service.ts
  src/services/exam.service.ts
Labels: :recycle: refactor

#146 [Deploy] 오타 수정
  src/controllers/auth.controller.ts
  src/swagger/openapi.yaml
Labels: :recycle: refactor

#148 [#147] QA : 사용자 정보 입력 예외 처리 수정
  src/repositories/user.repository.ts
Labels: :recycle: refactor

#149 [Deploy] QA 검토 수정
  src/repositories/user.repository.ts
Labels: :recycle: refactor

#156 [#151] 유사 사용자 - 기본 자격증 추천
  build/swagger.yaml
  src/repositories/user.repository.ts
  src/services/user.service.ts
Labels: :recycle: refactor
